### ISSUE TITLE
jrmapi/src/main/java/module-info.java:[5,25] module not found: net.lingala.zip4j

### ISSUE THREAD

**Issue by vorburger** [jlarriba/jrmapi#3] opened 2020-10-24 12:09 UTC
```
$ git clone git@github.com:jlarriba/jrmapi.git && cd jrmapi

$ mvn package
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jrmapi ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/vorburger/dev/Remarkable/jrmapi/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/vorburger/dev/Remarkable/jrmapi/src/main/java/module-info.java:[5,25] module not found: net.lingala.zip4j
[INFO] 1 error

$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode, sharing)

$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/vorburger/bin/apache-maven-3.6.3
Java version: 11.0.8, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.8.10-2.fc32.x86_64
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "5.8.14-200.fc32.x86_64", arch: "amd64", family: "unix"
```

**Comment by vorburger** [comment] 2020-10-24 12:13
`rm src/main/java/module-info.java` works around this.

**Comment by jlarriba** [comment] 2020-10-24 12:42
Hi,

thanks for your issue report. Astounding is a modular project for Java11, and I want it to keep being like this. The issue is that the developer of the zip4j library rejected my PR to modularize its library, as it would then require Java11 to compile:

https://github.com/srikanth-lingala/zip4j/pull/217

To solve this, I forked the zip4j library and modularized it:

https://github.com/jlarriba/zip4j

Download the source code, install it to your local repo and then build astounding.

I now realize that this is not very user friendly. I will close this Issue and open a new one to publish my own modularized zip4j under my own group "es.jlarriba" on central.

**Closed by jlarriba** 2020-10-24 12:42 UTC

**Comment by vorburger** [comment] 2020-10-24 16:50
@jlarriba thanks - understood. What I would probably do if I were you if I had to depend on pre-Java 11 libs was to write this project in Java 11, compile it with Java 11, use Java 11 syntax (`var`!) but just not put a `module-info.java`.. unless you want to have lots of fun with JPMS, it's "not worth" the overhead of having to maintain a fork of one of the libraries you use (including keep rebasing it - see #7). Just FYI I do that in my fork in https://github.com/jlarriba/jrmapi/compare/master...vorburger:vorburger (but that's not to say you should, just sharing a point of view).

**Comment by jlarriba** [comment] 2020-10-25 12:16
@vorburger  yeah, it is not bad advice. However, the idea was to iterate around JPMS to create thinner distributables.
